services:
  userservice:
    image: userservice
    container_name: userservice
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q
    depends_on:
      userservice-db:
        condition: service_healthy

  userservice-message-handler:
    image: userservice
    container_name: userservice-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q

      USER_AMQP_HOST: userservice-rmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest
    depends_on:
      userservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  userservice-db:
    image: "mysql:8.3"
    container_name: userservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "userservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: userservice_db
      MYSQL_USER: userservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  userservice-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: userservice-rmq
    hostname: userservice-rmq
    ports:
      - "15672:15672"
    volumes:
      - "userservice-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  userservice-db-data:
  userservice-rmq-data: