global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "userservice"
    static_configs:
      - targets:
          - "userservice:8082"
          - "userservice-workflow-worker:8082"
          - "userservice-message-handler:8082"
    metrics_path: /metrics

  - job_name: "temporal"
    static_configs:
      - targets:
          - "userservice-temporal:8000"
    metrics_path: /metrics
